# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    strategy: 
      matrix:
        go_version: ['1.19', '1.18', '>=1.19'] # Esse último é para passar alguma versão mais nova que 1.19
    
    steps:
    - uses: actions/checkout@v3
    
    - name: test Scret
      run: echo ${{ secrets.YOUR_SCRET_TEST_CI }} # nunca fazer isso em projeto real
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
        
    - name: Build-DB
      run: docker-compose build
    
    - name: Create-DB
      run: docker-compose up -d
      
    - name: Test
      run: go test -v main_test.go
      
  build:
    needs: test # Precisa que test tenha dado sucesso
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: go build -v main.go
